blog/blog/urls.py
from django.contrib import admin
from django.urls 	import include, path

urlpatterns = [
	path('blogs/', include('blogs.urls')),
    path('admin/', admin.site.urls),
]

blog/blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('signin/', views.signin, name = 'signin'),
    path('signup/', views.signup, name =' signup'),
    path('signuppage/', views.signuppage, name = 'signuppage'),
    path('welcome/', views.welcome, name = 'welcome'),
]

blog/blogs/models.py
from django.db         import models
from django.utils.html import format_html

class User(models.Model):
    USER_TYPES = (
        ('A', 'Administrator'),
        ('U', 'User'),
    )

    user_name = models.CharField(max_length = 20, primary_key = True)
    #TODO: Add protection against SQL Injection
    password  = models.CharField(max_length = 20)
    user_type = models.CharField(max_length = 1, choices = USER_TYPES)

    def __str__(self):
        return format_html('User Name: %s <br> Password: %s <br> User_type: %s' % (self.user_name,
                                                                                   self.password,
                                                                                   self.user_type))

    #TODO: Check if this function has any relevance
    def is_user_an_admin(self):
        return self.user_type == 'A'

blog/blogs/views.py
from django.shortcuts   import get_object_or_404, render
from django.urls        import reverse
from django.http        import HttpResponseRedirect

from .models import User

def index(request):
    if 'error_message' in request.session.keys(): del request.session['error_message'] 
    return render(request, 'blogs/index.html')

def signuppage(request):
    return render(request, 'blogs/signup.html')

def welcome(request):
    return render(request, 'blogs/welcome.html')

def signin(request):
    errorScenario = render(request, 'blogs/index.html', { 'error_message' : "Incorrect Username/Password!"})
    try:
        user = User.objects.get(pk = request.POST['user_name'])
    except(KeyError, User.DoesNotExist):
        return errorScenario
    else:
        if user.password == request.POST['password']:
            request.session["user_name"] = user.user_name
            return HttpResponseRedirect(reverse('blogs:welcome'))
        else:
            return errorScenario

def signup(request):
    if User.objects.filter(user_name=request.POST['user_name']).exists():
        request.session['error_message'] = "Username already exists!"
        return HttpResponseRedirect(reverse('blogs:signuppage'))
    else:
        User.objects.create(user_name=request.POST['user_name'], password=request.POST['password'], user_type='U')
        request.session["message"] = "Sign-Up Success!"
        return HttpResponseRedirect(reverse('blogs:index'))

blog/blogs/templates/blogs/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>The Blog Sign-In Page</title>
    </head>
    <body>
        <center>
            {% if error_message %}<p><strong>{{ message }}</strong></p>{% endif %}

            <h1>Welcome to the Blog Sign-In Page!</h1><br><br>

            <form action="{% url 'blogs:signin' %}" method="post">
                {% csrf_token %}
                <label for="user_name">Username: </label><br>
                <input type="text" id="user_name" name="user_name" onfocus="this.value=''" required><br>
                <label for="password">Password: </label><br>
                <input type="password" id="password" name="password" required><br><br>
                <input type="submit" value="Sign-In">
            </form>
            <button><a href="{% url 'blogs:signuppage' %}">Sign-Up</a></button>
        </center>
    </body>
</html>

blog/blogs/templates/blogs/signup.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>The Blog Sign-Up Page</title>
    </head>
    <body>
        <center>
            {% if request.session.error_message %}<p><strong>{{ request.session.error_message }}</strong></p>{% endif %}

            <h1>Welcome to the Blog Sign-Up Page!</h1><br><br>

            <form action="{% url 'blogs:signup' %}" method="post">
                {% csrf_token %}
                <label for="user_name">Username: </label><br>
                <input type="text" id="user_name" name="user_name" required><br>
                <label for="password">Password: </label><br>
                <input type="password" id="password" name="password" required><br><br>
                <input type="submit" value="Sign-Up">
            </form>
            <button><a href="{% url 'blogs:index' %}">Cancel</a></button>
        </center>
    </body>
</html>

blog/blogs/templates/blogs/welcome.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome to The Blog!</title>
    </head>
    <body>
        <center>
            <h1>Welcome to the Blog {{ request.session.user_name }}!</h1><br><br>
        </center>
    </body>
</html>